import cors from "cors";
import express from "express";
import { marked } from "marked";
import puppeteer from "puppeteer";

const app = express();
const port = Number(process.env.PORT || 8080);
const allowedOrigin = String(process.env.ALLOWED_ORIGIN || "*").trim() || "*";

app.disable("x-powered-by");
app.use(express.json({ limit: "2mb" }));
app.use(
  cors({
    origin(origin, callback) {
      if (!origin || allowedOrigin === "*" || origin === allowedOrigin) {
        callback(null, true);
        return;
      }
      callback(new Error("Origin not allowed"));
    }
  })
);

app.get("/health", (_req, res) => {
  res.status(200).json({
    ok: true,
    service: "o2o-pdf-export-service",
    now: new Date().toISOString()
  });
});

app.post("/api/export/pdf", async (req, res) => {
  const markdown = cleanText(req.body && req.body.markdown, 200000);
  const title = cleanText(req.body && req.body.title, 200) || "o2o-system";

  if (!markdown) {
    res.status(400).json({ ok: false, message: "Field markdown is required." });
    return;
  }

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined
    });

    const page = await browser.newPage();
    await page.setContent(buildHtmlDocument(markdown, title), { waitUntil: "networkidle0" });
    await page.emulateMediaType("screen");

    const pdfBytes = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "18mm",
        right: "14mm",
        bottom: "18mm",
        left: "14mm"
      }
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${safeFileName(title)}.pdf"`);
    res.status(200).send(pdfBytes);
  } catch (error) {
    const message = error && error.message ? error.message : "PDF generation failed";
    res.status(500).json({ ok: false, message });
  } finally {
    if (browser) {
      await browser.close();
    }
  }
});

app.listen(port, () => {
  console.log(`PDF export service listening on http://localhost:${port}`);
});

function buildHtmlDocument(markdown, title) {
  marked.setOptions({ gfm: true, breaks: true });
  const unsafeHtml = marked.parse(markdown);
  const contentHtml = stripUnsafeHtml(String(unsafeHtml || ""));

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)}</title>
    <style>
      :root {
        --ink: #132238;
        --muted: #4a5e78;
        --paper: #ffffff;
        --line: #d8e0ea;
        --accent: #0f5ea8;
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        color: var(--ink);
        background: var(--paper);
        font-family: "Segoe UI", "Helvetica Neue", Arial, sans-serif;
        line-height: 1.5;
        font-size: 12pt;
      }

      main {
        max-width: 190mm;
        margin: 0 auto;
      }

      h1,
      h2,
      h3,
      h4,
      h5,
      h6 {
        color: var(--ink);
        line-height: 1.2;
        margin: 1.1em 0 0.45em;
      }

      h1 {
        border-bottom: 2px solid var(--line);
        padding-bottom: 0.4em;
        font-size: 24pt;
      }

      h2 {
        font-size: 16pt;
        margin-top: 1.4em;
      }

      h3 {
        font-size: 13pt;
        color: var(--accent);
      }

      p {
        margin: 0.45em 0;
      }

      ul,
      ol {
        margin: 0.35em 0 0.9em 1.3em;
        padding: 0;
      }

      li {
        margin: 0.2em 0;
      }

      table {
        width: 100%;
        border-collapse: collapse;
        margin: 0.8em 0;
      }

      th,
      td {
        border: 1px solid var(--line);
        padding: 8px 10px;
        vertical-align: top;
      }

      th {
        background: #f3f7fb;
        text-align: left;
      }

      code {
        background: #f3f7fb;
        border: 1px solid var(--line);
        border-radius: 4px;
        padding: 1px 4px;
        font-size: 90%;
      }

      pre {
        background: #f3f7fb;
        border: 1px solid var(--line);
        border-radius: 6px;
        padding: 10px 12px;
        overflow-wrap: anywhere;
      }

      blockquote {
        border-left: 4px solid var(--line);
        color: var(--muted);
        margin: 0.8em 0;
        padding: 0.2em 0 0.2em 0.9em;
      }

      .footer {
        margin-top: 24px;
        color: var(--muted);
        font-size: 10pt;
      }
    </style>
  </head>
  <body>
    <main>
      ${contentHtml}
      <p class="footer">Generated by O2O Engine at ${escapeHtml(new Date().toISOString())}</p>
    </main>
  </body>
</html>`;
}

function stripUnsafeHtml(html) {
  return html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "")
    .replace(/\son[a-z]+=\"[^\"]*\"/gi, "")
    .replace(/\son[a-z]+=\'[^\']*\'/gi, "")
    .replace(/\sjavascript:/gi, "");
}

function cleanText(value, maxLength) {
  return String(value || "").replace(/\u0000/g, "").trim().slice(0, maxLength);
}

function safeFileName(input) {
  return cleanText(input, 120)
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-") || "o2o-system";
}

function escapeHtml(input) {
  return String(input || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
